# Generated by Django 5.2.3 on 2025-06-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(db_column='ID_Cuenta', primary_key=True, serialize=False)),
                ('numero_cuenta', models.CharField(db_column='Numero_Cuenta', max_length=20, unique=True)),
                ('tipo', models.CharField(db_column='Tipo', max_length=9)),
                ('saldo', models.DecimalField(db_column='Saldo', decimal_places=2, max_digits=10)),
                ('estado', models.CharField(db_column='Estado', max_length=8)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.AutoField(db_column='ID_Log', primary_key=True, serialize=False)),
                ('accion', models.CharField(db_column='Accion', max_length=255)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(db_column='ID_Transaccion', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=13)),
                ('cantidad', models.DecimalField(db_column='Cantidad', decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('estado', models.CharField(db_column='Estado', max_length=10)),
            ],
            options={
                'db_table': 'transaccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('correo_electronico', models.CharField(db_column='Correo_Electronico', max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('contrasena', models.CharField(db_column='Contrasena', max_length=255)),
                ('tipo', models.CharField(db_column='Tipo', max_length=8)),
                ('fecha_registro', models.DateTimeField(blank=True, db_column='Fecha_Registro', null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
